### ISSUE TITLE
not enough cats

### ISSUE THREAD

**Issue by ktan17** [jamieliu386/jamieliu.me#1]
more cats

**Comment by jamieliu386** [comment]
Thank you kindly for your input. We currently do not have quite enough manpower to support your request, but we will be adding this to the forefront of our priorities and will address this ASAP.

**Comment by mattxwang** [comment]
@ktan17 is there an app made with SwiftUI and the traditional MVVM model where I could learn more about cats?

**Comment by ktan17** [comment]
@malsf21 no but is there a president of a club teaching underserved students in the LA area computer science who could maybe lend his supreme dev skills here?
